### ISSUE TITLE
Pixel Data padded to even length is not preserved when changing transfer syntax

### ISSUE THREAD

**Issue by larsbjornfot** [fo-dicom/fo-dicom#1403]
**Describe the bug**
When changing the transfer syntax of a dataset where the Pixel Data is padded to even length, the padding is lost and the result is an odd-length Pixel Data. This is invalid DICOM. Pixel Data must always have even length. This happens when changing the transfer syntax of local files, and also in DICOM transfers to servers that requires changing transfer syntax. 

**To Reproduce**
Load a dataset with padded Pixel Data, for example a Secondary Capture RGB dataset with odd Rows and odd Columns.
Change the transfer syntax e.g. from Explicit Little Endian to Implicit Little Endian.
The result has odd-length PixelData. 

Sample code:
```
DicomFile file = DicomFile.Open(@"1.2.752.37.60.57594394193443685755042073672551662411.dcm");
var transcoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax, DicomTransferSyntax.ImplicitVRLittleEndian);

var newFile = transcoder.Transcode(file);
var pixelData = newFile.Dataset.GetDicomItem<DicomOtherWord>(DicomTag.PixelData);
var length = pixelData.Length; // Odd length is illegal
```

**Expected behavior**
The byte array in PixelData should remain padded and have even length.

**Screenshots or test DICOM files**

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10, x64
Platform: .NET 6

**Comment by mrbean-bremen** [comment]
This indeed looks like the padding is not added in the case of transforming data from an uncompressed to another uncompressed transfer syntax. Other cases that transform from or to an encapsulated dataset are handled by the codecs provider (e.g. fo-dicom.Codecs), so these cases shall be correct.

**Comment by gofal** [comment]
I'd like to verify this issue will be fixed with a PR. Therefore I now try to reproduce this issue in current dev-branch and check if the issue is fixed in PR.
But sadly, I cannot find a file in my personal repository to reproduce this. could you provide an anonymized file?

**Comment by mrbean-bremen** [comment]
Check my old (closed) PR #1404, I had a simple test image there, and a unit test.

**Comment by larsbjornfot** [comment]
I attach a small sample with PixelData in OB. The sample in PR #1404<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffo-dicom%2Ffo-dicom%2Fpull%2F1404&data=05%7C01%7Clars%40hermesmedical.com%7C926eff6486914cd5b42d08dae97bfc9f%7Ce6cdb1c888064ca0ae0b9f0b1921308a%7C1%7C0%7C638079015979633876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KRgpbQDCy7QZyt%2FsvEvf8SnyrT1yzbJuiv21OgUO5%2Bk%3D&reserved=0> has PixelData in OW. It’s worth testing both since OB data may be converted to OW at the same time it changes from Explicit to Implicit Little Endian.

**Comment by larsbjornfot** [comment]
Here is a small sample with PixelData in OB. The sample in PR #1404 has PixelData in OW. It’s worth testing both since OB data may be converted to OW at the same time it changes from Explicit to Implicit Little Endian. 
[1403-OB.zip](https://github.com/fo-dicom/fo-dicom/files/10331556/1403-OB.zip)

**Comment by ck2e14** [comment]
Hi, is there any further update on this? Many thanks

**Comment by jaime-olivares** [comment]
Hi all,
What is the conclusion here? I am reading about a similar issue in fo-dicom.Codecs: https://github.com/Efferent-Health/fo-dicom.Codecs/issues/36 

Where should this be fixed?

**Comment by mrbean-bremen** [comment]
@jaime-olivares - This issue happend only with with the transfer from/to uncompressed syntaxes, so it seems not to be related to that issue. It should be fixed in fo-dicom (or is already fixed? I'm a bit confused here).

**Comment by larsbjornfot** [comment]
I think this bug is not fixed, i.e. the special case where an uncompressed data set changes from Explicit to Implicit little endian. This also means Pixel Data changes from OB to OW. See my sample [1403-OB.zip](https://github.com/fo-dicom/fo-dicom/files/10331556/1403-OB.zip). 

I believe it would be fixed by https://github.com/fo-dicom/fo-dicom/pull/1494, that was closed with a motivation like "OW is always even length and need no padding".  But when OB changes to OW it seems padding is needed.

**Comment by jaime-olivares** [comment]
FYI. The issue in fo-dicom codecs has been fixed.

**Comment by larsbjornfot** [comment]
I updated to fo-dicom 5.1.1 (nuget package). The sample I uploaded [1403-OB.zip](https://github.com/fo-dicom/fo-dicom/files/10331556/1403-OB.zip) still fails to write even length when converted to Implicit Little Endian (which has OW value representation). 

Sample code:
```
void ExplicitByteToImplicitWord()
{
    var file = DicomFile.Open("1403-OB.dcm");
    var dicomTranscoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax,
        DicomTransferSyntax.ImplicitVRLittleEndian);
    var newFile = dicomTranscoder.Transcode(file);
    var dicomOtherWord = newFile.Dataset.GetDicomItem<DicomOtherWord>(DicomTag.PixelData);
    var length = dicomOtherWord.Length;
    Console.WriteLine($"length {length}"); // Odd length, illegal
    newFile.Save(@"output-newFile.dcm");
}
```

The dcmdump output shows a warning and Length = 27. Should be padded to 28 bytes.
```
$ dcmdump +L +P PixelData output-newFile.dcm
W: DcmItem: Length of element (7fe0,0010) is odd
(7fe0,0010) OW 0011\2200\0000\0033\4400\0000\0055\6600\0000\0077\8800\0000\0099 #  27, 1 PixelData
```

So, it's getting better but is not yet fixed.
