### ISSUE TITLE
Stack overflow after sending large amount of requests

### ISSUE THREAD

**Issue by jbergstr** [fo-dicom/fo-dicom#985]
The reason for this problem as well as the exact conditions when it is triggered is somewhat challenging to pinpoint, but nonetheless I decided to create an issue just in case you happen to already have an idea what causes it.

If I create a `Dicom.Network.Client.DicomClient`, establish an association, and then proceed to send several hundreds of images over the same association using `DicomCStoreRequest`s, then after all images have been sent and the association is about to be closed, the process terminates due to a stack overflow.

If I run the code as a console application being debugged in Visual Studio, I first see "Process terminated due to StackOverflowException." being printed. Then Visual Studio enters break mode, but no stack trace is available and VS suggests that the exception occurred in framework or external code.

As a first measure to circumvent this issue, I tried setting `Dicom.Network.Client.DicomClient.MaximumNumberOfRequestsPerAssociation` but it didn't really help. (I may have just been imagining this, but the setting perhaps slightly affected how soon StackOverflowException would get thrown, but the whole issue may not have anything to do with it.) Eventually the process would still crash when I reached somewhere betweed 800 and 1000 images sent.

Finally I found a just about tolerable workaround: after e.g. 200 images having been sent, I discard the currently used `DicomClient` and create a new one. So that at least seems to limit the cause to exist somewhere in the `DicomClient` implementation.

(fo-dicom 4.0.4 on .NET 4.7.1)

**Comment by amoerie** [comment]
Possibly related: https://stackoverflow.com/questions/32412426/unexpected-stack-overflow-despite-yielding

**Comment by amoerie** [comment]
Note: the MaximumNumberOfRequestsPerAssociation influences when the association is released, causing the DicomClient to move through the [SENDING] -> [REQUESTING_ASSOCIATION] states again, which would reset the KeepSendingUntilAllRequestsHaveCompletedAsync stack depth. So if the recursive call to KeepSendingUntilAllRequestsHaveCompletedAsync was the cause, I would expect this setting to avoid the problem..

**Comment by amoerie** [comment]
I have been experimenting a little with this and I'm afraid I cannot reproduce your problem. 
If you could add provide a console application or unit test that displays the problem, I'll be happy to take a look at it, but until then I won't spend more time on it, I hope you'll understand.

**Comment by jbergstr** [comment]
@amoerie Certainly, it's impossible to do anything about a thing you can't reproduce. I'll try to create a simplified console example program as time permits.

**Comment by amoerie** [comment]
@jbergstr someone else had a similar issue because of very deep stack traces in the timeout detection. This has been fixed by replacing the recursion with a while loop, and I applied the same fix in the sending requests state of the DicomClient. This has just been released, please give 4.0.6. a try and see if that fixes your problem. 🙂

**Comment by gofal** [comment]
So this issue should have been fixed with version 4.0.6? @jbergstr can you please verify?

**Comment by jbergstr** [comment]
Sorry for not responding, I've been away for the summer :)

Unfortunately even in 4.0.6 I'm still experiencing the same problem. After sending a bit over 900 requests over a single association, the process still crashes with a StackOverflowException.

I'll have to try to set aside some time at work to be able to produce a simplified example for reproducing the problem.

**Comment by amoerie** [comment]
In that case your StackOverflow is probably related to the many states your DicomClient is going through. We have a discussion going on here about introducing a new API for DicomClient: https://github.com/fo-dicom/fo-dicom/issues/1096

This new API is a definite solution for this problem. I still have to investigate if I could fix this issue without breaking the public API. A simple code sample that reproduces this problem would be useful though. :-)

**Comment by amoerie** [comment]
So, I can provide an update here:

the new DicomClient is (nearly) ready and merged, and the public API of DicomClient is (largely) untouched. It no longer uses a state pattern internally, but the corresponding OnStateChanged event is still supported for backwards compatibility.

You can still use DicomClient like before, or you can use a more AdvancedDicomClient which provides lower level control over the connection, association and request sending. Note that you do lose a bunch of DicomClient features such as "MaximumRequestsPerAssociation". 

See  #1144
